### ISSUE TITLE
STEM and diagrams enabling

### ISSUE THREAD

**Issue by m-titov** [manoelcampos/asciidoctor-ghpages-action#16]
How to enable the https://asciidoctor.org/docs/asciidoctor-diagram/ and https://docs.asciidoctor.org/asciidoc/latest/stem/stem/ ?

I tried to do it by adding the 'Install plantuml' and 'Install gnuplot' steps into asciidoctor-ghpages.yml but it seems doesn't work:
```
name: asciidoctor-ghpages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install plantuml
        run: sudo apt-get install -y plantuml

      - name: Install gnuplot
        run: sudo apt-get install -y gnuplot

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          asciidoctor_params: --attribute=nofooter
          pdf_build: true
```
